### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by gregoryalary** [clementbosc/celcat2ics#1]
I can't get a response from [celcat2ics.clementbosc.fr](https://celcat2ics.clementbosc.fr).

**Comment by clementbosc** [comment]
Back again ! Thank you for noticing 👍

**Comment by DylanAbdou** [comment]
hi, i can't get a reponse too !

**Comment by clementbosc** [comment]
Yes I know, sorry about that. I don't plan to put it online again right
away, so you can clone my repo and host it your self if you want 🙂 don't
hesitate to share the new link with us in comment below !
Clement

Le dim. 15 sept. 2019 à 23:26, DylanAbdou <notifications@github.com> a
écrit :
